// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOVofuKjFSgPBWlZKJy4zFw_mPo-qbDw',
    appId: '1:635736355222:web:fd16f8562a50ee084fadb7',
    messagingSenderId: '635736355222',
    projectId: 'dobara-ca7ca',
    authDomain: 'dobara-ca7ca.firebaseapp.com',
    storageBucket: 'dobara-ca7ca.firebasestorage.app',
    measurementId: 'G-RGSC7B5MWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPal7DxHirA6mvvzX0eICLN_7LzWegbck',
    appId: '1:635736355222:android:4a0ff3356966cd3a4fadb7',
    messagingSenderId: '635736355222',
    projectId: 'dobara-ca7ca',
    storageBucket: 'dobara-ca7ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMjH6pBCcVzBOXTow9Gugj6VE570NSrE',
    appId: '1:635736355222:ios:d100d7376162ebe44fadb7',
    messagingSenderId: '635736355222',
    projectId: 'dobara-ca7ca',
    storageBucket: 'dobara-ca7ca.firebasestorage.app',
    iosBundleId: 'com.fahadbhatti.dobara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMjH6pBCcVzBOXTow9Gugj6VE570NSrE',
    appId: '1:635736355222:ios:d100d7376162ebe44fadb7',
    messagingSenderId: '635736355222',
    projectId: 'dobara-ca7ca',
    storageBucket: 'dobara-ca7ca.firebasestorage.app',
    iosBundleId: 'com.fahadbhatti.dobara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOVofuKjFSgPBWlZKJy4zFw_mPo-qbDw',
    appId: '1:635736355222:web:f7e5d0d70e075b7e4fadb7',
    messagingSenderId: '635736355222',
    projectId: 'dobara-ca7ca',
    authDomain: 'dobara-ca7ca.firebaseapp.com',
    storageBucket: 'dobara-ca7ca.firebasestorage.app',
    measurementId: 'G-GY4KC9D5LB',
  );
}
